lists/urls.py
from django.conf.urls import url
from django.contrib import admin
from lists import views


urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

superlists/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from lists import views
from lists import urls as list_urls


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home'),
    url(r'^lists/', include(list_urls))
]

lists/models.py
from django.db import models

# Create your models here.


class List(models.Model):
	pass

class Item(models.Model):
	"""docstring for Item"""
	text = models.TextField(default='')
	list = models.ForeignKey(List, default=None)




		

lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from lists.models import Item, List
# Create your views here.

# home_page = None

def home_page(request):
	return render(request, 'home.html')


def view_list(request, list_id):
	list_ = List.objects.get(id=list_id)
	# items = Item.objects.filter(list=list_)
	# return render(request, 'list.html', {'items': items})
	return render(request, 'list.html', {'list': list_})


def new_list(request):
	list_ = List.objects.create()
	Item.objects.create(text=request.POST['item_text'], list=list_)
	return redirect(f'/lists/{list_.id}/')


def add_item(request,list_id):
	list_ = List.objects.get(id=list_id)
	Item.objects.create(text=request.POST['item_text'], list=list_)
	return redirect(f'/lists/{list_.id}/')

lists/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <!-- <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="/static/boostrap/css/boostrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/base.css">

  </head>


  <body>
    <!-- <h1>Hello, world!</h1>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) 
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script> -->

    <div class="container">

      <div class="row">
        <div class="col_md_6 col-md-offset-3 jumbotron">
          <div class="test-center">
            <h1>{% block header_text %}{% endblock %}</h1>
              <form method="POST" action="{% block form_action %}{% endblock %}">
                <input class="form-control input-lg" name="item_text" id="id_new_item" placeholder="Enter a to do item"/>
                {% csrf_token %}
              </form>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset 3">
          {% block table %}
          {% endblock %}
        </div>
      </div>

      
    </div>

  </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %}Start a new To-Do list{% endblock %}
{% block form_action %}/lists/new{% endblock %}

lists/templates/list.html
<!DOCTYPE html>
<html>
<head>
	<title>To-Do lists</title>
</head>
<body>

	<h1>To-Do lists</h1>
	<form method="POST" action="/lists/{{list.id}}/add_item">
		<input name="item_text" id='id_new_item' placeholder="Enter a to-do item" />
		{% csrf_token %}
	</form>
	<table id="id_list_table" class="table">
		{% for item in list.item_set.all %}
		<tr><td>{{ forloop.counter }}:{{ item.text }}</td></tr>
		{% endfor %}
	</table>
</body>
</html>